CREATE DATABASE mydb CHARACTER SET utf8 COLLATE utf8_bin;
#secret
CREATE USER 'rohit'@'%' IDENTIFIED BY PASSWORD '*14E65567ABDB5135D0CFD9A70B3032C179A49EE7';
# can fail if user exists
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE TEMPORARY TABLES ON tmp.* TO rohit@localhost;

#GRANT ALL ON mydb TO 'rohit'@'%';
#GRANT CREATE ON mydb TO 'rohit'@'%';
FLUSH PRIVILEGES;
